### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by dsyer** [spring-guides/gs-messaging-gcp-pubsub#2]
This is a guide about pubsub, not about gcp in general. I would suggest `gs-messaging-google-pubsub` would be a better name.

**Comment by meltsufin** [comment]
Who can make this change? I would prefer `gs-spring-cloud-gcp-pubsub`.

**Comment by gregturn** [comment]
Leave that to me once it's decided.

**Comment by gregturn** [comment]
I would look at the other guides to consider a consistent name. For example "Messaging with Redis".

**Comment by meltsufin** [comment]
Thanks @gregturn! I see the pattern and David's suggestion makes sense, with a small tweak:
`gs-messaging-gcp-pubsub`. Let's go with that, unless anyone has objections.

**Comment by artembilan** [comment]
No objection! The `gs-messaging-gcp-pubsub` be it!

**Comment by gregturn** [comment]
Okay. I'll carry that out later today.

**Comment by gregturn** [comment]
Done
